TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 8
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  PATH_TO_DATA_DIR: /home/cheweili/WLASL/WLASL/TimeSformer/prepare_dataset/WLASL2000
  NUM_FRAMES: 8
  SAMPLING_RATE: 16
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224 
  INPUT_CHANNEL_NUM: [3]
  PATH_PREFIX: /home/cheweili/WLASL/WLASL/TimeSformer/prepare_dataset/WLASL2000
  PATH_LABEL_SEPARATOR: ' '
  DECODING_BACKEND: pyav
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
SOLVER:
  BASE_LR: 0.001   #from 0.0005 chg to 0.001
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 11, 14]
  LRS: [1, 0.1, 0.01]

  MAX_EPOCH: 60
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 2001
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.3    #from 0.1 chg to 0.3 
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 0
  PIN_MEMORY: False
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
